return {
    SpriteRenderer = import("./SpriteRenderer"),
    Transform = import("./Transform"),
    Rigidbody = import("./Rigidbody"),
    FrameAnimation = import("./FrameAnimation"),
    Camera = import("./Camera"),
    PanController = import("./camera/PanController"),
    Collider = import("./Collider"),
    TileCollider = import("./TileCollider"),
    Tilemap = import("./Tilemap"),
    Label = import("./Label")
};