return {
    SpriteRenderSystem = import("./SpriteRenderSystem"),
    RigidbodySystem = import("./RigidbodySystem"),
    FrameAnimationSystem = import("./FrameAnimationSystem"),
    CameraSystem = import("./CameraSystem"),
    PanControllerSystem = import("./PanControllerSystem"),
    TilemapCollisionSystem = import("./TilemapCollisionSystem"),
    CollisionSystem = import("./CollisionSystem"),
    TilemapRenderSystem = import("./TilemapRenderSystem"),
    LabelRenderSystem = import("./LabelRenderSystem")
};