#pragma once

/* 
!!!! THIS FILE WAS GENERATED BY THE compile.py PYTHON SCRIPT !!!
!!!! PLEASE RUN THE SCRIPT AGAIN TO UPDATE !!!!
*/

extern "C" {
#include <melon/core/vm.h>
}

extern "C" {
TRet boundingboxModuleInit(VM* vm);
}

namespace kola {
namespace scripting {

extern const char* BOUNDINGBOX_MODULE_SOURCE;

} // namespace scripting
} // namespace kola