/* 
!!!! THIS FILE WAS GENERATED BY THE compile.py PYTHON SCRIPT !!!
!!!! PLEASE RUN THE SCRIPT AGAIN TO UPDATE !!!!
*/

#include "kolanut/scripting/melon/modules/SpriteModule.h"
#include "kolanut/scripting/melon/modules/SourceModule.h"

extern "C" {

TRet spriteModuleInit(VM* vm)
{
    return sourceModuleInit(vm, "builtin::Sprite.ms", kola::scripting::SPRITE_MODULE_SOURCE);
}

}

namespace kola {
namespace scripting {

const char* SPRITE_MODULE_SOURCE = R"##ENDSOURCE##(
return {
    create = |name| => {
        return { 
            pos = Vector.create(0.0, 0.0),
            angle = 0.0,
            scale = Vector.create(1.0, 1.0),
            texture = Kolanut.loadSprite(name)
        } @ Sprite;
    },

    draw = => {
        this.texture->draw(
            this.pos.x, this.pos.y,
            this.angle,
            this.scale.x, this.scale.y
        );
    }
};
)##ENDSOURCE##";

} // namespace scripting
} // namespace kola