name: Windows

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: windows-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    strategy:
      fail-fast: false
      matrix:
        bits: [64]
        include:
        - bits: 64
          ARCH: "x86_64"
          MSYSTEM: "MINGW64"

    steps:
    - name: Install Vulkan
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.170.0/windows/VulkanSDK-1.2.170.0-Installer.exe" -OutFile VulkanSDK.exe
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{ matrix.MSYSTEM }}
        install: "base-devel mingw-w64-${{ matrix.ARCH }}-toolchain mingw-w64-${{ matrix.ARCH }}-lld"

    - uses: actions/checkout@master
      with:
        ssh-key: "${{ secrets.SSH_KEY }}"
        submodules: "recursive"
        
    - name: Setup BUILD_32 ON
      run: |
        echo "::set-env name=BUILD_32::ON"
        echo "::set-env name=BUILD_BITS::32"
      shell: bash
      if: matrix.bits == 32
    
    - name: Setup BUILD_32 OFF
      run: |
        echo "::set-env name=BUILD_32::OFF"
        echo "::set-env name=BUILD_BITS::64"
      shell: bash
      if: matrix.bits == 64

    - name: "Updates shaderc dependencies"
      shell: msys2 {0}
      run: |
        cd "${{ github.workspace }}/src/kolanut/libs/shaderc"
        ./utils/git-sync-deps
        
    - name: Run CMake
      shell: msys2 {0}
      run: |
        cd "${{ github.workspace }}"
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_VULKAN -G "MSYS Makefiles" ../
    
    - name: Run Make
      run: |
        cd "${{ github.workspace }}\\build"
        make
      shell: msys2 {0}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kolanut-windows-${{ env.BUILD_BITS }}
        path: "${{ github.workspace }}\\build\\kolanut.exe"
